service: serverless-crud

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getAllAuthors:
    handler: handler.getAllAuthors
    name: getAllAuthors
    events:
      - http:
          path: authors
          method: get
          cors: true
