service: serverless-crud

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-sequelize-migrations

custom:
  migrationsPath: './database/migrations'
  dotenv:
    basepath: ./
    logging: false

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DB_DIALECT: ${env:DB_DIALECT}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}

functions:
  allAuthors:
    handler: handler.allAuthors
    name: allAuthors
    events:
      - http:
          path: authors
          method: get
          cors: true

  storeAuthor:
    handler: handler.storeAuthor
    name: storeAuthor
    events:
      - http:
          path: author
          method: post
          cors: true

  updateAuthor:
    handler: handler.updateAuthor
    name: updateAuthor
    events:
      - http:
          path: author/{id}
          method: put
          cors: true

  deleteAuthor:
    handler: handler.deleteAuthor
    name: deleteAuthor
    events:
      - http:
          path: author/{id}
          method: delete
          cors: true

  allPublications:
    handler: handler.allPublications
    name: allPublications
    events:
      - http:
          path: publications
          method: get
          cors: true
